name: C:\Users\sunny\OneDrive\Desktop\LIVE_demo\ANN-implementation-DLCVNLP-demo\envs
channels:
  - defaults
dependencies:
  - ca-certificates=2021.7.5=haa95532_1
  - certifi=2021.5.30=py37haa95532_0
  - openssl=1.1.1l=h2bbff1b_0
  - pip=21.0.1=py37haa95532_0
  - python=3.7.11=h6244533_0
  - setuptools=58.0.4=py37haa95532_0
  - sqlite=3.36.0=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.0=pyhd3eb1b0_1
  - wincertstore=0.2=py37haa95532_2
  - pip:
    - absl-py==0.14.1
    - astunparse==1.6.3
    - cached-property==1.5.2
    - cachetools==4.2.4
    - charset-normalizer==2.0.6
    - clang==5.0
    - cycler==0.10.0
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.41.0
    - h5py==3.1.0
    - idna==3.2
    - importlib-metadata==4.8.1
    - keras==2.6.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - markdown==3.3.4
    - matplotlib==3.4.3
    - numpy==1.19.5
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - pandas==1.3.3
    - pillow==8.3.2
    - protobuf==3.18.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytz==2021.3
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scipy==1.7.1
    - seaborn==0.11.2
    - six==1.15.0
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.6.0
    - tensorflow-estimator==2.6.0
    - termcolor==1.1.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.7
    - werkzeug==2.0.1
    - wrapt==1.12.1
    - zipp==3.6.0
prefix: C:\Users\sunny\OneDrive\Desktop\LIVE_demo\ANN-implementation-DLCVNLP-demo\envs
